### ISSUE TITLE
Try auto code generation for TES specification

### ISSUE THREAD

**Issue by uniqueg** [elixir-cloud-aai/ga4gh-sdk#12]
- [x] Check [Open API tooling](https://tools.openapis.org/) to see if there are auto code generators for OpenAPI available in Rust
- [ ] Explore available code generators and create table listing maintenance status and features
- [x] Try to auto generate client code and or models for [TES API version 1.1](https://github.com/ga4gh/task-execution-schemas/releases/tag/v1.1)

**Comment by aaravm** [comment]
We can do this using https://openapi-generator.tech/docs/generators/rust/ 
<br>
I tried this on [TES API version 1.1](https://github.com/ga4gh/task-execution-schemas/releases/tag/v1.1) and I generated https://github.com/aaravm/tes-library-rust-autogenerated

**Comment by aaravm** [comment]
I also tried for wes specification:
https://github.com/aaravm/wes_openapi

**Comment by uniqueg** [comment]
Good stuff. As far as I can tell, this looks pretty decent. Maybe the comments could use some work (wrap/multi lines?). Apart from that, I guess we will have to see if we run into problems with the generated models. I think that in another (Python) project the auto-generated models for TES needed to lightly amended. I will see if I find more info on that.

I suggest that you create a PR to merge the models, docs and whatever else seems necessary (for now only for TES) into the main project and ask @vemonet and @pavelnikonorov for reviews.

**Comment by uniqueg** [comment]
[Here] are the auto-generated TES 1.0.0 Pydantic models. And I think [here](https://github.com/elixir-cloud-aai/openapi-test-runner/commit/a5024e152ff900248136d4f489529a0f23c929eb) are the manual changes (I guess you can ignore the TESK-specific changes, but for the others, please have a look and see if they are indeed required by the specs but not picked up by the auto-generated models).
